name: test practice
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x, 16.x]

    steps:
      - name: Show ubuntu details
          run: lsb_release -a
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: npm install
        run: npm ci
      - name: tests
        run: npm test
